In [263]:
import numpy as np
np.set_printoptions(precision=4)
import pandas as pd
from sklearn import linear_model

In [322]:
df=pd.read_csv('Prostate.csv')
data=np.array(df)
x,y=data[:,0:8],data[:,8:9]
n=x.shape[0]
b=np.ones(n).reshape(n,-1)
x2=np.hstack((x,b))

In [345]:
def ols(x,y):
    beta=np.linalg.inv(x.T@x)@x.T@y
    return beta
ols(x2,y)
lr=linear_model.LinearRegression(fit_intercept=False)
lr.fit(x2,y)
print(ols(x2,y).T,'\n',lr.coef_)

[[ 0.587   0.4545 -0.0196  0.1071  0.7662 -0.1055  0.0451  0.0045  0.6694]] 
 [[ 0.587   0.4545 -0.0196  0.1071  0.7662 -0.1055  0.0451  0.0045  0.6694]]


In [347]:
def smt(X):
    n,p=X.shape[0],X.shape[1]
    Q=np.zeros_like(X)
    t=0
    for x in X.T:
        v=x.copy()
        for i in range(t):
            v-=Q[:,i].T@x*Q[:,i]
        Q[:,t]=v/np.linalg.norm(v)
        t+=1
    return Q
def sur(x,y):
    n,p=x.shape[0],x.shape[1]
    x0=np.ones(n).reshape(n,-1)
    x=np.hstack((x0,x))
    q=smt(x)
    beta=[q[:,i].T@y/np.linalg.norm(q[:,i],2) for i in range(p+1)]
    return beta

In [348]:
np.set_printoptions(precision=4)
# smt(x)
sur(x,y)


[array([24.4093]),
 array([8.3068]),
 array([2.4389]),
 array([-0.6481]),
 array([1.0339]),
 array([2.4396]),
 array([-0.3595]),
 array([0.8411]),
 array([0.7251])]

In [285]:
import numpy as np  
A = x  
Q = np.zeros_like(A)  
m = Q.shape[0]  
n = Q.shape[1]  
cnt = 0  
for a in A.T:  
    u = np.copy(a)  
    for i in range(0, cnt):  
        u -= np.dot(np.dot(Q[:, i].T, a), Q[:, i]) # 减去待求向量在以求向量上的投影  
    e = u / np.linalg.norm(u)  # 归一化  
    Q[:, cnt] = e  
    cnt += 1  