In [1]:
import numpy as np
np.set_printoptions(precision=4)
import pandas as pd
from sklearn import linear_model

In [2]:
df=pd.read_csv('Prostate.csv')
data=np.array(df)
x,y=data[:,0:8],data[:,8:9]
n=x.shape[0]
b=np.ones(n).reshape(n,-1)
x2=np.hstack((b,x))

In [12]:
#Regression by Successive Orthogonalization
def sor(X,y):
    n,p=X.shape[0],X.shape[1]
    Q=np.zeros_like(X)
    Q[:,0]=np.ones(n)
    l=0
    beta_list=[]
    for x in X.T:
        v=x.copy()
        for i in range(l):
            l2_sq=Q[:,i].T@Q[:,i]
            v-=Q[:,i].T@x/l2_sq*Q[:,i]
        Q[:,l]=v
        beta=v.T@y/(v.T@v)
        beta_list.append(beta)
        l+=1
    return Q,beta_list

In [10]:
#use fomula
def ols(x,y):
    beta=np.linalg.inv(x.T@x)@x.T@y
    return beta
#use package
lr=linear_model.LinearRegression(fit_intercept=False)
lr.fit(x2,y)
print(ols(x2,y).T,'\n',lr.coef_)

[[ 0.6694  0.587   0.4545 -0.0196  0.1071  0.7662 -0.1055  0.0451  0.0045]] 
 [[ 0.6694  0.587   0.4545 -0.0196  0.1071  0.7662 -0.1055  0.0451  0.0045]]


In [13]:
#use 'sor'
fit=sor(x2,y)
Q,beta=fit[0],fit[1]
#Q is an orthogonal matrix
print(q.T@q)
beta

[array([2.4784]),
 array([0.7193]),
 array([0.5109]),
 array([-0.0095]),
 array([0.084]),
 array([0.721]),
 array([-0.0412]),
 array([0.1459]),
 array([0.0045])]